version: 2.1

# 오브를 호출합니다
# 오브엔 실행환경, 환경변수 작업, 명령이 미리 구성되어 있습니다
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

# 작업을 정의한다
# https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  viewCode:
    # 실행환경을 지정한다, CircleCI, DockerHub에서 이미지를 지정할 수 있습니다
    # https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Code tree"
          command: "ls -al"
  BuildTest:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: "install npm module"
          command: |
            cd src
            npm i
      - run:
          name: "build project"
          command: |
            cd src
            npm run build
  createEnv:
    machine: true
    steps:
      - checkout
      - run:
          name: "Create .env file"
          command: |
            cd src
            ../.circleci/scripts/generate-env-files.sh
            ls -al

# 워크플로우를 정의합니다
workflows:
  # 빌드 테스트 워크플로우
  Build-Test:
    jobs:
      - BuildTest:
          filters:
            branches:
              only: /TIL\/.*/
  # 이미지 푸시
  build_and_push_image:
    jobs:
      - createEnv:
          context:
            - TILOG_BACKEND_PROD
